GROUP=io.github.junggikim
VERSION_NAME=0.1.2
mavenCentralPublishing=true
signAllPublications=true
POM_NAME=Spring REST Docs Kotlin DSL
POM_DESCRIPTION=Kotlin DSL for Spring REST Docs and restdocs-api-spec.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/JunggiKim/spring-restdocs-kotlin-dsl
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/JunggiKim/spring-restdocs-kotlin-dsl
POM_SCM_CONNECTION=scm:git:git://github.com/JunggiKim/spring-restdocs-kotlin-dsl.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/JunggiKim/spring-restdocs-kotlin-dsl.git
POM_DEVELOPER_ID=JunggiKim
POM_DEVELOPER_NAME=Junggi Kim
POM_DEVELOPER_URL=https://github.com/JunggiKim
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
